# Generated by Django 3.0.6 on 2020-07-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200727_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='totalDislikes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='totalFollower',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='totalLikes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
