# Generated by Django 3.0.6 on 2020-07-30 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200730_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='totalComment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='totalFollower',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='follower_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
