# Generated by Django 3.0.6 on 2020-07-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20200731_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
